### ISSUE TITLE
Change the inside text color of two buttons.

### ISSUE THREAD

**Issue by gravitydestroyer** [lugnitdgp/GLUG-app#1]
Change the inside text color of two buttons with id "btn_skip" and "btn_next" of the activity_welcome.xml layout.

activity_welcome.xml layout is located inside the layout folder.

Change the black color of the text inside those two buttons and set them to a color with hex code #501075.

**Comment by PushpikaWan** [comment]
Can I work on this issue?

**Comment by PushpikaWan** [comment]
I made a pull request to your GitHub repo #9. thank you
